-- database: The_prince.db
CREATE TABLE IF NOT EXISTS PNJ (
    idPNJ INTEGER PRIMARY KEY AUTOINCREMENT,
    nom TEXT NOT NULL,
    role TEXT DEFAULT 'paysan'
);
ALTER TABLE PNJ ADD COLUMN ambition INTEGER DEFAULT 20 CHECK(ambition BETWEEN 0 AND 100);
ALTER TABLE PNJ ADD COLUMN loyaute INTEGER DEFAULT 70 CHECK(loyaute BETWEEN 0 AND 100);
ALTER TABLE PNJ ADD COLUMN est_joueur BOOLEAN DEFAULT 0;
