-- database: The_prince.db
CREATE TABLE IF NOT EXISTS PNJ (
    idPNJ INTEGER PRIMARY KEY AUTOINCREMENT,
    nom TEXT NOT NULL,
    role TEXT DEFAULT 'paysan'
);
ALTER TABLE PNJ ADD COLUMN ambition INTEGER DEFAULT 20 CHECK(ambition BETWEEN 0 AND 100);
ALTER TABLE PNJ ADD COLUMN loyaute INTEGER DEFAULT 70 CHECK(loyaute BETWEEN 0 AND 100);
ALTER TABLE PNJ ADD COLUMN est_joueur BOOLEAN DEFAULT 0;


CREATE TABLE IF NOT EXISTS complots (
    idComplot INTEGER PRIMARY KEY AUTOINCREMENT,
    initiateur_id INTEGER,
    cible_id INTEGER,
    reussi BOOLEAN,
    FOREIGN KEY (initiateur_id) REFERENCES PNJ(idPNJ),
    FOREIGN KEY (cible_id) REFERENCES PNJ(idPNJ)
);


CREATE TABLE IF NOT EXISTS royaume (
    id INTEGER PRIMARY KEY CHECK (id = 1),
    jours INTEGER DEFAULT 1
);
