[project]
name = "the-prince"
version = "0.1.0"
description = "3D engine in Python"
readme = "README.md"
requires-python = ">=3.12,<3.13"

dependencies = [
    "glfw>=2.10.2",
    "numpy>=2.5.3",
    "pyopengl>=3.1.10",
    "pyopengl-accelerate>=3.1.10",
]

[project.scripts]
the-prince = "main:main"

[build-system]
requires = ["uv_build>=0.12.15,<0.13.0"]
build-backend = "uv_build"

[tool.uv.build-backend]
module-name = "engine"
module-root = ""

[tool.pytest.ini_options]
pythonpath = ["."]
testpaths = ["tests"]

[dependency-groups]
dev = [
    "hypothesis>=6.168.1",
    "pytest>=9.1.1",
]
